import {
	Activity,
	Atom,
	AudioLines,
	Binary,
	BookA,
	Bookmark,
	BookOpen,
	Bot,
	Boxes,
	Braces,
	Brain,
	BrainCircuit,
	Briefcase,
	Bug,
	Calculator,
	Camera,
	ChartColumn,
	ChartLine,
	ChartPie,
	ChartScatter,
	ChartSpline,
	Cloud,
	CloudCog,
	Code,
	CodeXml,
	Container,
	Cpu,
	Database,
	DatabaseZap,
	Dna,
	Dumbbell,
	Feather,
	FileSpreadsheet,
	FlaskConical,
	Folder,
	Gamepad2,
	GitBranch,
	Globe,
	GraduationCap,
	Heart,
	HeartPulse,
	Hospital,
	KeyRound,
	Landmark,
	Languages,
	Laptop,
	Leaf,
	Library,
	Lightbulb,
	Magnet,
	Map,
	MessagesSquare,
	Microscope,
	Music,
	Network,
	Notebook,
	NotebookPen,
	Orbit,
	Palette,
	PawPrint,
	Percent,
	Pi,
	Pill,
	Plane,
	Quote,
	Radical,
	Rocket,
	Scale,
	ScanText,
	School,
	Server,
	ServerCog,
	Sheet,
	ShieldCheck,
	Sigma,
	Sparkles,
	SpellCheck,
	SquareFunction,
	Star,
	Stethoscope,
	Syringe,
	Table,
	Tablets,
	Telescope,
	Terminal,
	TestTube,
	TestTubes,
	TextQuote,
	TrendingUp,
	Trophy,
	Type,
	Utensils,
	Variable,
	Waypoints,
	WholeWord,
	Workflow,
	Zap,
} from 'lucide-react';

// Deck and folder symbols are stored as one of these keys (deckSymbol /
// folderSymbol). Keys are persisted in user data, so never rename or remove
// one. Anything unknown - including emoji saved by older versions of the
// app - falls back to the default icon for that container type.
export const CONTAINER_ICON_GROUPS = [
	{
		label: 'General',
		icons: {
			'book-open': BookOpen,
			folder: Folder,
			library: Library,
			notebook: Notebook,
			'notebook-pen': NotebookPen,
			bookmark: Bookmark,
			'graduation-cap': GraduationCap,
			school: School,
			lightbulb: Lightbulb,
			star: Star,
			trophy: Trophy,
			rocket: Rocket,
		},
	},
	{
		label: 'Cloud & Infrastructure',
		icons: {
			cloud: Cloud,
			'cloud-cog': CloudCog,
			server: Server,
			'server-cog': ServerCog,
			network: Network,
			container: Container,
			boxes: Boxes,
			workflow: Workflow,
			'shield-check': ShieldCheck,
			key: KeyRound,
			globe: Globe,
		},
	},
	{
		label: 'Programming & CS',
		icons: {
			code: Code,
			'code-xml': CodeXml,
			braces: Braces,
			terminal: Terminal,
			cpu: Cpu,
			binary: Binary,
			'git-branch': GitBranch,
			bug: Bug,
			laptop: Laptop,
		},
	},
	{
		label: 'Data & SQL',
		icons: {
			database: Database,
			'database-zap': DatabaseZap,
			table: Table,
			sheet: Sheet,
			spreadsheet: FileSpreadsheet,
		},
	},
	{
		label: 'AI & Machine Learning',
		icons: {
			brain: Brain,
			'brain-circuit': BrainCircuit,
			waypoints: Waypoints,
			bot: Bot,
			sparkles: Sparkles,
		},
	},
	{
		label: 'Language & NLP',
		icons: {
			languages: Languages,
			'book-a': BookA,
			'spell-check': SpellCheck,
			'whole-word': WholeWord,
			type: Type,
			messages: MessagesSquare,
			quote: Quote,
			'text-quote': TextQuote,
			'scan-text': ScanText,
			'audio-lines': AudioLines,
		},
	},
	{
		label: 'Statistics & Math',
		icons: {
			'chart-column': ChartColumn,
			'chart-line': ChartLine,
			'chart-scatter': ChartScatter,
			'chart-spline': ChartSpline,
			'chart-pie': ChartPie,
			'trending-up': TrendingUp,
			sigma: Sigma,
			function: SquareFunction,
			variable: Variable,
			pi: Pi,
			radical: Radical,
			percent: Percent,
			calculator: Calculator,
		},
	},
	{
		label: 'Medicine & Pharmacy',
		icons: {
			pill: Pill,
			tablets: Tablets,
			syringe: Syringe,
			stethoscope: Stethoscope,
			'heart-pulse': HeartPulse,
			activity: Activity,
			hospital: Hospital,
			microscope: Microscope,
			dna: Dna,
			'test-tube': TestTube,
			'test-tubes': TestTubes,
			flask: FlaskConical,
		},
	},
	{
		label: 'Science',
		icons: {
			atom: Atom,
			orbit: Orbit,
			telescope: Telescope,
			magnet: Magnet,
			zap: Zap,
			leaf: Leaf,
		},
	},
	{
		label: 'Other',
		icons: {
			landmark: Landmark,
			scale: Scale,
			briefcase: Briefcase,
			heart: Heart,
			music: Music,
			palette: Palette,
			feather: Feather,
			camera: Camera,
			utensils: Utensils,
			dumbbell: Dumbbell,
			gamepad: Gamepad2,
			plane: Plane,
			map: Map,
			paw: PawPrint,
		},
	},
];

export const CONTAINER_ICONS = Object.assign(
	{},
	...CONTAINER_ICON_GROUPS.map((group) => group.icons)
);

export const DEFAULT_DECK_ICON = 'book-open';
export const DEFAULT_FOLDER_ICON = 'folder';

export function resolveContainerIcon(name, isFolder = false) {
	return (
		CONTAINER_ICONS[name] ||
		CONTAINER_ICONS[isFolder ? DEFAULT_FOLDER_ICON : DEFAULT_DECK_ICON]
	);
}

// Normalize a stored symbol to a valid icon key (legacy emoji -> default)
export function normalizeContainerIcon(name, isFolder = false) {
	if (CONTAINER_ICONS[name]) return name;
	return isFolder ? DEFAULT_FOLDER_ICON : DEFAULT_DECK_ICON;
}
